import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/utlis/providers/ReactQueryProvider";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import ThemeProviders from "@/utlis/providers/themeProvider";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders>
          <ReactQueryProvider>
            <Theme>{children}</Theme>
          </ReactQueryProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
